steps:
- name: 'gcr.io/cloud-builders/go'
  env:
    - GOPATH=/workspace
  args: [
  'build', '-o', '/workspace/gcp-iap-auth'
  ]
  # build docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [
  'build',
  '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME',
  '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$REVISION_ID',
  '.'
  ]

images:
- 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME'
- 'gcr.io/$PROJECT_ID/$REPO_NAME:$REVISION_ID'
