steps:
- name: 'gcr.io/cloud-builders/go'
  env:
    - GOPATH=/workspace
    - GO15VENDOREXPERIMENT=1
  args: [
  'build',
  '-o', './build/gcp-iap-auth'
  ]
  # build docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [
  'build',
  '-t', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME',
  '.'
  ]

images:
- 'eu.gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME'
